import random

MelbStreetNames = [
    "Abbotsford",
 "Aberfeldie",
 "Airport West",
 "Albanvale",
 "Albert Park",
 "Albion",
 "Alphington",
 "Altona Meadows",
 "Altona North",
 "Altona",
 "Ardeer",
 "Armadale",
 "Arthurs Seat",
 "Ascot Vale",
 "Ashburton",
 "Ashwood",
 "Aspendale",
 "Aspendale Gardens",
 "Attwood",
 "Auburn",
 "Aurora",
 "Avondale Heights",
 "Avonsleigh",
 "Balaclava",
 "Balwyn",
 "Balwyn North",
 "Bangholme",
 "Baxter",
 "Bayswater",
 "Bayswater North",
 "Beaconsfield",
 "Beaumaris",
 "Belgrave",
 "Belgrave Heights",
 "Belgrave South",
 "Bellfield",
 "Bennettswood",
 "Bentleigh",
 "Bentleigh East",
 "Berwick",
 "Bittern",
 "Black Rock",
 "Blackburn",
 "Blackburn North",
 "Blackburn South",
 "Blairgowrie",
 "Bonbeach",
 "Boronia",
 "Box Hill",
 "Box Hill North",
 "Box Hill South",
 "Braeside",
 "Braybrook",
 "Briar Hill",
 "Brighton",
 "Brighton East",
 "Broadmeadows",
 "Brookfield",
 "Brooklyn",
 "Brunswick",
 "Brunswick East",
 "Brunswick West",
 "Bulla",
 "Bulleen",
 "Bundoora",
 "Burnley",
 "Burnside",
 "Burnside Heights",
 "Burwood",
 "Burwood East",
 "Cairnlea",
 "Calder Park",
 "Camberwell",
 "Campbellfield",
 "Canterbury",
 "Carlton North",
 "Carlton",
 "Carnegie",
 "Caroline Springs",
 "Carrum",
 "Carrum Downs",
 "Caulfield",
 "Caulfield East",
 "Caulfield North",
 "Caulfield South",
 "Chadstone",
 "Chelsea",
 "Chelsea Heights",
 "Cheltenham",
 "Chirnside Park",
 "Clarinda",
 "Clayton",
 "Clayton South",
 "Clematis",
 "Clifton Hill",
 "Coburg",
 "Coburg North",
 "Cocoroc",
 "Coldstream",
 "Collingwood",
 "Coolaroo",
 "Craigieburn",
 "Cranbourne",
 "Cranbourne East",
 "Cranbourne North",
 "Cranbourne South",
 "Cranbourne West",
 "Cremorne",
 "Crib Point",
 "Croydon",
 "Croydon Hills",
 "Croydon North",
 "Croydon South",
 "Dallas",
 "Dandenong",
 "Dandenong North",
 "Dandenong South",
 "Deer Park",
 "Delahey",
 "Derrimut",
 "Diamond Creek",
 "Dingley Village",
 "Docklands",
 "Doncaster",
 "Doncaster East",
 "Donvale",
 "Doreen",
 "Doveton",
 "Dromana",
 "Eaglemont",
 "East Melbourne",
 "Edithvale",
 "Elsternwick",
 "Eltham",
 "Eltham North",
 "Elwood",
 "Emerald",
 "Endeavour Hills",
 "Epping",
 "Essendon Fields",
 "Essendon North",
 "Essendon West",
 "Essendon",
 "Eumemmerring",
 "Fairfield",
 "Fawkner",
 "Ferntree Gully",
 "Ferny Creek",
 "Fitzroy",
 "Fitzroy North",
 "Flemington",
 "Footscray",
 "Forest Hill",
 "Frankston",
 "Frankston North",
 "Frankston South",
 "Gardenvale",
 "Gladstone Park",
 "Glen Huntly",
 "Glen Iris",
 "Glen Waverley",
 "Glenroy",
 "Gowanbrae",
 "Greensborough",
 "Greenvale Lakes",
 "Greenvale",
 "Guys Hill",
 "Hadfield",
 "Hallam",
 "Hampton",
 "Hampton East",
 "Hampton Park",
 "Harkaway",
 "Hawthorn",
 "Hawthorn East",
 "Heatherdale",
 "Heatherton",
 "Heathmont",
 "Heidelberg",
 "Heidelberg Heights",
 "Heidelberg West",
 "Highett",
 "Hillside",
 "Hoppers Crossing",
 "Houston",
 "Hughesdale",
 "Huntingdale",
 "Hurstbridge",
 "Ivanhoe",
 "Ivanhoe East",
 "Jacana",
 "Junction Village",
 "Kallista",
 "Kalorama",
 "Karingal",
 "Kealba",
 "Keilor",
 "Keilor Downs",
 "Keilor East",
 "Keilor Lodge",
 "Keilor North",
 "Keilor Park",
 "Kensington",
 "Kerrimuir",
 "Kew",
 "Kew East",
 "Keysborough",
 "Kilsyth",
 "Kilsyth South",
 "Kings Park",
 "Kingsbury",
 "Kingsville",
 "Knoxfield",
 "Kooyong",
 "Kurunjang",
 "Laburnum",
 "Lalor",
 "Langwarrin",
 "Langwarrin South",
 "Laverton",
 "Laverton North",
 "Lilydale",
 "Lower Plenty",
 "Lynbrook",
 "Lyndhurst",
 "Lysterfield",
 "Lysterfield South",
 "Macclesfield",
 "McCrae",
 "McKinnon",
 "Macleod",
 "Maidstone",
 "Malvern",
 "Malvern East",
 "Maribyrnong",
 "Meadow Heights",
 "Melbourne Airport",
 "Melton (suburb)",
 "Melton South",
 "Melton West",
 "Mentone",
 "Menzies Creek",
 "Mernda",
 "Mickleham",
 "Middle Park",
 "Milgate Park Estate",
 "Mill Park",
 "Mitcham",
 "Monbulk",
 "Mont Albert",
 "Mont Albert North",
 "Montmorency",
 "Montrose",
 "Moonee Ponds",
 "Moorabbin Airport",
 "Moorabbin",
 "Moorooduc",
 "Mooroolbark",
 "Mordialloc",
 "Mornington",
 "Mount Dandenong",
 "Mount Eliza",
 "Mount Evelyn",
 "Mount Martha",
 "Mount Waverley",
 "Mulgrave",
 "Narre Warren East",
 "Narre Warren North",
 "Narre Warren South",
 "Narre Warren",
 "Newport",
 "Niddrie",
 "Noble Park",
 "Noble Park North",
 "North Melbourne",
 "North Richmond",
 "North Warrandyte",
 "Northcote",
 "Norwood",
 "Notting Hill",
 "Nunawading",
 "Oak Park",
 "Oaklands Junction",
 "Oakleigh",
 "Oakleigh East",
 "Oakleigh South",
 "Olinda",
 "Olivers Hill",
 "Ormond",
 "Pakenham",
 "Panton Hill",
 "Park Orchards",
 "Parkdale",
 "Parkville",
 "Pascoe Vale South",
 "Pascoe Vale",
 "The Patch",
 "Patterson Lakes",
 "Pennydale",
 "Plenty",
 "Point Cook",
 "Port Melbourne",
 "Portsea",
 "Prahran",
 "Preston",
 "Princes Hill",
 "Ravenhall",
 "Research",
 "Reservoir",
 "Richmond",
 "Ringwood",
 "Ringwood East",
 "Ringwood North",
 "Ripponlea",
 "Rockbank",
 "Rosanna",
 "Rosebud",
 "Rosebud West",
 "Rowville",
 "Roxburgh Park",
 "Rye",
 "Safety Beach",
 "St Albans",
 "St Helena",
 "St Kilda",
 "St Kilda East",
 "St Kilda West",
 "Sandhurst",
 "Sandringham",
 "Sassafras",
 "Scoresby",
 "Seabrook",
 "Seaford",
 "Seaholme",
 "Seddon",
 "Selby",
 "Seville",
 "Sherbrooke",
 "Skye",
 "Somerton",
 "Sorrento",
 "South Kingsville",
 "South Melbourne",
 "South Morang",
 "South Wharf",
 "South Yarra",
 "Southbank",
 "Spotswood",
 "Springvale",
 "Springvale South",
 "Strathmore",
 "Strathmore Heights",
 "Sunbury",
 "Sunshine",
 "Sunshine North",
 "Sunshine West",
 "Surrey Hills",
 "Sydenham",
 "Syndal",
 "Tally Ho",
 "Tarneit",
 "Taylors Hill",
 "Taylors Lakes",
 "Tecoma",
 "Templestowe",
 "Templestowe Lower",
 "The Basin",
 "Thomastown",
 "Thornbury",
 "Toorak",
 "Tootgarook",
 "Tottenham",
 "Travancore",
 "Tremont",
 "Truganina",
 "Tullamarine",
 "Upfield",
 "Upper Ferntree Gully",
 "Upwey",
 "Vermont",
 "Vermont South",
 "Viewbank",
 "Wantirna",
 "Wantirna South",
 "Warrandyte",
 "Warrandyte South",
 "Warranwood",
 "Waterways",
 "Watsonia",
 "Watsonia North",
 "Wattle Glen",
 "Waverley Park",
 "Werribee",
 "Werribee South",
 "West Footscray",
 "West Melbourne",
 "Westgarth",
 "Westmeadows",
 "Wheelers Hill",
 "Wildwood",
 "Williams Landing",
 "Williamstown",
 "Williamstown North",
 "Windsor",
 "Wonga Park",
 "Wyndham Vale",
 "Yallambie",
 "Yarrambat",
 "Yarraville",
 "Yuroke",
]
validAddress = []

if __name__ == '__main__':
    with open("test.txt", "w") as file:
        
        #! GENERATE RANDOM AGENT WITH WEIGHTS
        totalAgent = random.randint(6, 9)
        file.write(f'AGENT,{totalAgent},')

        for i in range(totalAgent):
            if i != totalAgent -1:
                file.write(f'{random.randint(25, 50)},')
            else:
                file.write(f'{random.randint(25, 50)}\n')

        #! GENERATE RANDOM LOCATION THAT THE AGENT CAN VISIT
        totalNodes = random.randint(10, 20)


        for i in range(totalNodes):
            posX = random.randint(15,645)
            posY = random.randint(15,410)
            nodeName = random.choice(MelbStreetNames)

            file.write(f'NODE,{posX},{posY},{nodeName}\n')
            MelbStreetNames.remove(nodeName)
            validAddress.append(nodeName)
        
        #! GENERATE RANDOM PARCELS THAT THE AGENT NEEED TO DELIVER
        totalParcels = random.randint(25, 50)

        for i in range(totalParcels):
            weight = random.randint(5, 25)
            destination = random.choice(validAddress)

            if i != totalAgent -1:
                file.write(f'PARCEL,{weight},{destination},{destination.split(" ", 1)[0]}\'s Parcel\n')
            else:
                file.write(f'PARCEL,{weight},{destination},{destination.split(" ", 1)[0]}\'s Parcel')




        
        